---
apiVersion: front.in-cloud.io/v1alpha1
kind: TableUriMapping
metadata:
  name: monitoring-detail
spec:
  id: "default-/apps.cozystack.io/v1alpha1/monitorings"
  pathToNavigate: "/openapi-ui/{clusterName}/{namespace}/factory/monitoring-detail/~recordValue~"
  keysToParse:
    - metadata
    - name

---

apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: apps-cozystack-monitoring-detail
spec:
  id: "default-/apps.cozystack.io/v1alpha1/monitorings"
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.namespace
      name: Namespace
      type: string
    - jsonPath: .status.version
      name: Version
      type: string

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: factory-monitoring-detail-metrics-storages
spec:
  id: "factory-monitoring-detail-metrics-storages"
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .deduplicationInterval
      name: DeduplicationInterval
      type: string
    - jsonPath: .retentionPeriod
      name: RetentionPeriod
      type: string
    - jsonPath: .storage
      name: Storage
      type: string
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: factory-monitoring-detail-logs-storages
spec:
  id: "factory-monitoring-detail-logs-storages"
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .retentionPeriod
      name: RetentionPeriod
      type: string
    - jsonPath: .storage
      name: Storage
      type: string
    - jsonPath: .storageClassName
      name: StorageClass
      type: string
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: factory-monitoring-detail-status-conditions
spec:
  id: "factory-monitoring-detail-status-conditions"
  additionalPrinterColumns:
    - jsonPath: .type
      name: Type
      type: string
    - jsonPath: .status
      name: Status
      type: string
    - jsonPath: .lastTransitionTime
      name: LastTransitionTime
      type: date
    - jsonPath: .message
      name: Message
      type: string
  additionalPrinterColumnsUndefinedValues:
    - key: Message
      value: "-"
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Factory
metadata:
  name: monitoring-detail
spec:
  key: monitoring-detail
  withScrollableMainContentCard: true
  urlsToFetch:
    - "/api/clusters/{2}/k8s/apis/apps.cozystack.io/v1alpha1/namespaces/{3}/monitorings/{6}"
  data:
    - type: antdTabs
      data:
        id: 30
        defaultActiveKey: "details"
        items:
          - key: "details"
            label: "Details"
            children:
              # — General details card
              - type: ContentCard
                data:
                  id: 2100
                  style:
                    marginBottom: 24px
                children:
                  - type: antdText
                    data:
                      id: 2101
                      text: "Monitoring details"
                      strong: true
                      style:
                        fontSize: 20
                        marginBottom: 12px
                  - type: Spacer
                    data:
                      id: 2101-spacer
                      "$space": 16
                  - type: antdRow
                    data:
                      id: 2102
                      gutter: [48, 12]
                    children:
                      - type: antdCol
                        data:
                          id: 2103
                          span: 12
                        children:
                          - type: antdFlex
                            data:
                              id: 2104
                              vertical: true
                              gap: 24
                            children:
                              - type: antdFlex
                                data:
                                  id: 2105
                                  vertical: true
                                  gap: 4
                                children:
                                  - type: antdText
                                    data:
                                      id: 21051
                                      strong: true
                                      text: "Name"
                                  - type: parsedText
                                    data:
                                      id: 21052
                                      text: "{reqs[0]['metadata','name']}"
                              - type: antdFlex
                                data:
                                  id: 2106
                                  vertical: true
                                  gap: 4
                                children:
                                  - type: antdText
                                    data:
                                      id: 21061
                                      strong: true
                                      text: "Namespace"
                                  - type: parsedText
                                    data:
                                      id: 21062
                                      text: "{reqs[0]['metadata','namespace']}"
                              - type: antdFlex
                                data:
                                  id: 2107
                                  vertical: true
                                  gap: 4
                                children:
                                  - type: antdText
                                    data:
                                      id: 21071
                                      strong: true
                                      text: "Version"
                                  - type: parsedText
                                    data:
                                      id: 21072
                                      text: "{reqs[0]['status','version']}"
                      - type: antdCol
                        data:
                          id: 2120
                          span: 12
                        children:
                          # Grafana section
                          - type: ContentCard
                            data:
                              id: 2150
                              style:
                                marginBottom: 24px
                            children:
                              - type: antdText
                                data:
                                  id: 2151
                                  text: "Grafana Configuration"
                                  strong: true
                              - type: Spacer
                                data:
                                  id: 2152
                                  "$space": 8
                              - type: antdFlex
                                data:
                                  id: 2153
                                  vertical: true
                                  gap: 4
                                children:
                                  - type: antdFlex
                                    data:
                                      id: 21531
                                      vertical: true
                                      gap: 4
                                    children:
                                      - type: antdText
                                        data:
                                          id: 215311
                                          strong: true
                                          text: "Host"
                                      - type: parsedText
                                        data:
                                          id: 215312
                                          text: "{reqs[0]['spec','grafana','host']}"
                          # Alerta section
                          - type: ContentCard
                            data:
                              id: 2160
                              style:
                                marginBottom: 24px
                            children:
                              - type: antdText
                                data:
                                  id: 2161
                                  text: "Alerta Configuration"
                                  strong: true
                              - type: Spacer
                                data:
                                  id: 2162
                                  "$space": 8
                              - type: antdFlex
                                data:
                                  id: 2163
                                  vertical: true
                                  gap: 4
                                children:
                                  - type: antdFlex
                                    data:
                                      id: 21631
                                      vertical: true
                                      gap: 4
                                    children:
                                      - type: antdText
                                        data:
                                          id: 216311
                                          strong: true
                                          text: "Storage"
                                      - type: parsedText
                                        data:
                                          id: 216312
                                          text: "{reqs[0]['spec','alerta','storage']}"
                                  - type: antdFlex
                                    data:
                                      id: 21632
                                      vertical: true
                                      gap: 4
                                    children:
                                      - type: antdText
                                        data:
                                          id: 216321
                                          strong: true
                                          text: "StorageClass"
                                      - type: parsedText
                                        data:
                                          id: 216322
                                          text: "{reqs[0]['spec','alerta','storageClassName']}"
              # Metrics Storages section
              - type: antdCol
                data:
                  id: 2201
                  style:
                    marginTop: 32px
                    padding: 16px
                children:
                  - type: antdText
                    data:
                      id: 22011
                      text: "Metrics Storages"
                      strong: true
                      style:
                        fontSize: 22
                  - type: EnrichedTable
                    data:
                      id: 22012
                      baseprefix: "/openapi-ui"
                      clusterNamePartOfUrl: "{2}"
                      fetchUrl: "/api/clusters/{2}/k8s/apis/apps.cozystack.io/v1alpha1/namespaces/{3}/monitorings/{6}"
                      customizationId: "factory-monitoring-detail-metrics-storages"
                      withoutControls: true
                      pathToItems:
                        - spec
                        - metricsStorages
              # Logs Storages section
              - type: antdCol
                data:
                  id: 2301
                  style:
                    marginTop: 32px
                    padding: 16px
                children:
                  - type: antdText
                    data:
                      id: 23011
                      text: "Logs Storages"
                      strong: true
                      style:
                        fontSize: 22
                  - type: EnrichedTable
                    data:
                      id: 23012
                      baseprefix: "/openapi-ui"
                      clusterNamePartOfUrl: "{2}"
                      fetchUrl: "/api/clusters/{2}/k8s/apis/apps.cozystack.io/v1alpha1/namespaces/{3}/monitorings/{6}"
                      customizationId: "factory-monitoring-detail-logs-storages"
                      withoutControls: true
                      pathToItems:
                        - spec
                        - logsStorages
              # Conditions section
              - type: antdCol
                data:
                  id: 2401
                  style:
                    marginTop: 32px
                    padding: 16px
                children:
                  - type: antdText
                    data:
                      id: 24011
                      text: "Conditions"
                      strong: true
                      style:
                        fontSize: 22
                  - type: EnrichedTable
                    data:
                      id: 24012
                      baseprefix: "/openapi-ui"
                      clusterNamePartOfUrl: "{2}"
                      fetchUrl: "/api/clusters/{2}/k8s/apis/apps.cozystack.io/v1alpha1/namespaces/{3}/monitorings/{6}"
                      customizationId: "factory-monitoring-detail-status-conditions"
                      withoutControls: true
                      pathToItems:
                        - status
                        - conditions
          - key: "yaml"
            label: "Yaml"
            children: "Content of Tab Pane 2"
