---
apiVersion: front.in-cloud.io/v1alpha1
kind: TableUriMapping
metadata:
  name: namespaces
spec:
  id: default-/v1/namespaces
  pathToNavigate: "/openapi-ui/{clusterName}/~recordValue~/api-table/apps.cozystack.io/v1alpha1/virtualmachines"
  keysToParse:
    - metadata
    - name
